blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Feature Requests & Questions 
    url: https://github.com/sergiodxa/remix-i18next/discussions
    about: Please ask and answer questions here.